### ISSUE TITLE
Hello from Hiveeyes

### ISSUE THREAD

**Issue by amotl** [SBajonczak/hivemonitor#6]
Hallo Sascha,

vielen Dank fuer https://github.com/hiveeyes/hiveeyes-epaper-display/pull/4! Wir haben gesehen, dass Du hier die wunderbare Firmware [`node-wifi-mqtt-homie.ino`](https://github.com/hiveeyes/arduino/blob/master/node-wifi-mqtt-homie/node-wifi-mqtt-homie.ino) fuer Homie von @Gulaschcowboy weiterentwickelst und haben Dir deshalb gerade eben einen entsprechenden Artikel bei [1] spendiert.

Falls Du noch nicht Mitglied bei uns im Forum bist, freuen wir uns, wenn wir Dich dort ebenfalls begruessen koennen.

Herzliche Gruesse,
Andreas.

[1] https://community.hiveeyes.org/t/hive-monitor-software-von-sascha-bajonczak/3753

**Comment by amotl** [comment]
Hallo Sascha,

Du bist ja schon laengst dabei [2], ich konnte Dich nur nicht zuordnen. Herzlichen Dank und happy hacking!

Viele Gruesse,
Andreas.

[2] https://community.hiveeyes.org/t/hive-monitor-software-von-sascha-bajonczak/3753/3

**Comment by SBajonczak** [comment]
Genau, ihr seid ja in dem Portal eine suoer inspiration
